"""Initial schema with 3 core tables

Revision ID: 001
Revises: 
Create Date: 2024-01-01 00:00:00.000000

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '001'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    
    # Create users table
    op.create_table(
        'users',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('name', sa.String(length=100), nullable=False),
        sa.Column('email', sa.String(length=255), nullable=False),
        sa.Column('password_hash', sa.String(length=255), nullable=False),
        sa.Column('role', sa.Enum('patient', 'doctor', 'admin', name='userrole'), nullable=False),
        sa.Column('is_verified', sa.Boolean(), nullable=True),
        sa.Column('verification_token', sa.String(length=255), nullable=True),
        sa.Column('specialization', sa.String(length=100), nullable=True),
        sa.Column('primary_doctor_id', sa.Integer(), nullable=True),
        sa.Column('threshold_profile_id', sa.Integer(), nullable=True),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
        sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('email')
    )
    op.create_index('ix_users_email', 'users', ['email'], unique=False)
    op.create_index('ix_users_id', 'users', ['id'], unique=False)
    
    # Create weather_snapshots table
    op.create_table(
        'weather_snapshots',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('city', sa.String(length=100), nullable=False),
        sa.Column('latitude', sa.Float(), nullable=False),
        sa.Column('longitude', sa.Float(), nullable=False),
        sa.Column('pressure_hpa', sa.Float(), nullable=False),
        sa.Column('pressure_mmhg', sa.Integer(), nullable=False),
        sa.Column('temperature', sa.Float(), nullable=True),
        sa.Column('humidity', sa.Integer(), nullable=True),
        sa.Column('weather_description', sa.String(length=100), nullable=True),
        sa.Column('recorded_at', sa.DateTime(timezone=True), nullable=False),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_weather_snapshots_city', 'weather_snapshots', ['city'], unique=False)
    op.create_index('ix_weather_snapshots_id', 'weather_snapshots', ['id'], unique=False)
    op.create_index('ix_weather_snapshots_pressure_mmhg', 'weather_snapshots', ['pressure_mmhg'], unique=False)
    op.create_index('ix_weather_city_recorded', 'weather_snapshots', ['city', 'recorded_at'], unique=False)
    
    # Create measurements table
    op.create_table(
        'measurements',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('user_id', sa.Integer(), nullable=False),
        sa.Column('systolic', sa.Integer(), nullable=False),
        sa.Column('diastolic', sa.Integer(), nullable=False),
        sa.Column('pulse', sa.Integer(), nullable=True),
        sa.Column('measured_at', sa.DateTime(timezone=True), nullable=False),
        sa.Column('latitude', sa.Float(), nullable=True),
        sa.Column('longitude', sa.Float(), nullable=True),
        sa.Column('notes', sa.Text(), nullable=True),
        sa.Column('weather_snapshot_id', sa.Integer(), nullable=True),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
        sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
        sa.ForeignKeyConstraint(['weather_snapshot_id'], ['weather_snapshots.id'], ),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_measurements_id', 'measurements', ['id'], unique=False)
    op.create_index('ix_measurements_measured_at', 'measurements', ['measured_at'], unique=False)
    op.create_index('ix_measurements_user_id', 'measurements', ['user_id'], unique=False)
    
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_measurements_user_id', table_name='measurements')
    op.drop_index('ix_measurements_measured_at', table_name='measurements')
    op.drop_index('ix_measurements_id', table_name='measurements')
    op.drop_table('measurements')
    
    op.drop_index('ix_weather_city_recorded', table_name='weather_snapshots')
    op.drop_index('ix_weather_snapshots_pressure_mmhg', table_name='weather_snapshots')
    op.drop_index('ix_weather_snapshots_id', table_name='weather_snapshots')
    op.drop_index('ix_weather_snapshots_city', table_name='weather_snapshots')
    op.drop_table('weather_snapshots')
    
    op.drop_index('ix_users_id', table_name='users')
    op.drop_index('ix_users_email', table_name='users')
    op.drop_table('users')
    
    # Drop enum type
    op.execute('DROP TYPE IF EXISTS userrole')
    # ### end Alembic commands ###
